// This file is automatically generated. Do not edit it directly.
// Legacy Supabase client - replaced with MongoDB
// This file is kept to prevent import errors in components that haven't been updated yet

export const supabase = {
  // Placeholder object to prevent import errors
  // All functionality has been moved to the MongoDB API client
  auth: {
    signUp: () => Promise.resolve({ error: new Error('Use MongoDB API instead') }),
    signInWithPassword: () => Promise.resolve({ error: new Error('Use MongoDB API instead') }),
    signOut: () => Promise.resolve({ error: null }),
    getSession: () => Promise.resolve({ data: { session: null } }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } })
  },
  from: () => ({
    select: () => ({
      eq: () => Promise.resolve({ data: [], error: new Error('Use MongoDB API instead') })
    })
  })
};